import React from 'react'
import Layout from '@/components/Layout'
import Head from 'next/head'
import CourseList from '@/components/CourseList'

export default function UnconfirmedCourses() {
 

  return (
    <>
      <Head>
        <title>VEDUS | Onay Bekleyen Verilen Dersler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous"/>
      </Head>
      <Layout>
        <CourseList/>
      </Layout>
    </>
  )
}
