import React from 'react'
import Layout from '@/components/Layout'
import Head from 'next/head'

export default function contact() {
  return (
    <>
      <Head>
        <title>VEDUS | Bize Ulaşın</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous"/>
      </Head>
      <Layout>
      {/* <!-- Container for demo purpose --> */}
      <div className="container px-6 mx-auto">
        {/* <!-- Section: Design Block --> */}
        <section className="mb-10 text-gray-800">
          <div className="relative overflow-hidden bg-no-repeat bg-cover"
            style={{backgroundPosition: "50%", backgroundImage: "url('https://mdbootstrap.com/img/new/textures/full/284.jpg')",height: "300px"}}>
          </div>
          <div className="container text-gray-800 px-4 md:px-12">
            <div className="block rounded-lg shadow-lg py-10 md:py-12 px-2 md:px-6"
              style={{marginTop: "-100px", background: "hsla(0, 0%, 100%, 0.8)", backdropFilter: "blur(30px)"}}>
              <div className="flex flex-wrap">
                <div className="grow-0 shrink-0 basis-auto mb-6 md:mb-0 w-full md:w-6/12 px-3 lg:px-6">
                  <h2 className="text-3xl font-bold mb-6">Bizimle İletişime Geçin</h2>
                  <p className="text-gray-500 mb-6">Merhaba,</p>
                  <p className="text-gray-500 mb-6">
                  Bizimle iletişime geçmek için yandaki iletişim formunu doldurabilir, herhangi bir konuda bize ulaşabilirsiniz. Sorularınızı cevaplamaktan, geri bildirimlerinizi dinlemekten ve işbirliği tekliflerinizi değerlendirmekten mutluluk duyarız. Lütfen adınızı, e-posta adresinizi ve iletmek istediğiniz mesajınızı belirtmeyi unutmayın. Size en kısa sürede geri dönüş yapacağız.                    
                  </p>
                  <p className="text-gray-500 mb-6">
                  Müşteri memnuniyeti ve güçlü iş ilişkileri, işimizin temel değerleridir. Sizden duymak için sabırsızlanıyoruz!
                  </p>
                  <p className="text-gray-500 mb-2">New York, 94126, United States</p>
                  <p className="text-gray-500 mb-2">+ 01 234 567 89</p>
                  <p className="text-gray-500 mb-2">info@vedus.com</p>
                </div>
                <div className="grow-0 shrink-0 basis-auto mb-12 md:mb-0 w-full md:w-6/12 px-3 lg:px-6">
                  <form>
                    <div className="form-group mb-6">
                      <input type="text" className="form-control block
                        w-full
                        px-3
                        py-1.5
                        text-base
                        font-normal
                        text-gray-700
                        bg-white bg-clip-padding
                        border border-solid border-gray-300
                        rounded
                        transition
                        ease-in-out
                        m-0
                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="exampleInput7"
                        placeholder="Adınız"/>
                    </div>
                    <div className="form-group mb-6">
                      <input type="email" className="form-control block
                        w-full
                        px-3
                        py-1.5
                        text-base
                        font-normal
                        text-gray-700
                        bg-white bg-clip-padding
                        border border-solid border-gray-300
                        rounded
                        transition
                        ease-in-out
                        m-0
                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" id="exampleInput8"
                        placeholder="Email"/>
                    </div>
                    <div className="form-group mb-6">
                      <textarea className="
                        form-control
                        block
                        w-full
                        px-3
                        py-1.5
                        text-base
                        font-normal
                        text-gray-700
                        bg-white bg-clip-padding
                        border border-solid border-gray-300
                        rounded
                        transition
                        ease-in-out
                        m-0
                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
                      " id="exampleFormControlTextarea13" rows="3" placeholder="Mesaj"></textarea>
                    </div>
                    <button type="submit" className="
                      w-full
                      px-6
                      py-2.5
                      bg-blue-600
                      text-white
                      font-medium
                      text-xs
                      leading-tight
                      uppercase
                      rounded
                      shadow-md
                      hover:bg-blue-700 hover:shadow-lg
                      focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0
                      active:bg-blue-800 active:shadow-lg
                      transition
                      duration-150
                      ease-in-out">Gönder</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <!-- Section: Design Block --> */}
      </div>
      {/* <!-- Container for demo purpose --> */}
      </Layout>
    </>
  )
}
