import React from 'react'
import Layout from '@/components/Layout'
import Head from 'next/head'
import {
    MDBCol,
    MDBContainer,
    MDBRow,
    MDBCard,
    MDBCardBody,
    MDBBtn
  } from 'mdb-react-ui-kit';

export default function AddCourse() {
  return (
    <>
    <Head>
      <title>VEDUS | Ders Ekle</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous"/>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css" rel="stylesheet" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
    </Head>
    <Layout>
      <section>
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex items-baseline justify-between border-b border-gray-200 pb-6 pt-10">
              <h1 className="text-3xl font-bold tracking-tight text-gray-900">Ders Ekle :</h1>
            </div>
        </div>

        <div className="container py-4">
          <div className="lg:w-4/5 mx-auto flex flex-wrap">
            {/* Kişisel Bilgiler */}
            <MDBContainer>
                <MDBRow>
                    <MDBCol lg="4">
                        <MDBCard className="mb-4">
                        <MDBCardBody className="text-center">
                            <div className="mx-auto flex flex-wrap">
                            <img alt="ecommerce" className="mx-auto object-cover object-center rounded border border-gray-200" src="https://images.unsplash.com/photo-1537495329792-41ae41ad3bf0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"/>
                            </div>
                        </MDBCardBody>
                        </MDBCard>
                    </MDBCol>
                    <MDBCol lg="8">
                        <MDBCard className="mb-4">
                        <MDBCardBody>
                            <MDBRow>
                            <input type="text" name="first-name" id="first-name" placeholder="Ders İlanı Başlık" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
                            </MDBRow>
                            <hr />
                            <MDBRow>
                                <select id="category" name="category"
                                    className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                                    <option>Kategori Seçiniz</option>
                                    <option>Matematik</option>
                                    <option>Türkçe</option>
                                </select>
                            </MDBRow>
                            <hr />
                            <MDBRow>
                            <textarea id="description" name="description" rows="10" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder='İlan hakkında bir şeyler yaz...'></textarea>
                            </MDBRow>
                            <div className="mt-6 flex items-center justify-end gap-x-6" >
                                <MDBBtn type="submit"
                                    className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                                Ekle
                                </MDBBtn >
                            </div>
                        </MDBCardBody>
                        </MDBCard>
                    </MDBCol>
                </MDBRow>
            </MDBContainer>
          </div>
        </div>
      </section>
    </Layout>
  </>
  )
}

// import React from 'react'
// import { FaGlobe, FaLinkedin, FaInstagram } from "react-icons/fa";
// import { UserCircleIcon } from '@heroicons/react/24/solid'
// import Head from 'next/head'
// import Layout from '@/components/Layout'
// import {
//     MDBCol,
//     MDBContainer,
//     MDBRow,
//     MDBCard,
//     MDBCardBody,
//     MDBListGroup,
//     MDBListGroupItem,
//     MDBBtn
//   } from 'mdb-react-ui-kit';
  

// export default function AddCourse() {
//   return (
//     <>
//     <Head>
//       <title>VEDUS | Ders Ekle</title>
//       <meta name="description" content="Generated by create next app" />
//       <meta name="viewport" content="width=device-width, initial-scale=1" />
//       <link rel="icon" href="/favicon.ico" />
//       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous"/>
//     </Head>
//     <Layout>
//     <section>
//       <MDBContainer className="py-5">
//         <MDBRow>
//           {/* Kişisel Bilgiler */}
//           <MDBCol lg="8">
//             <MDBCard className="mb-4">
//               <MDBCardBody>
//                 <MDBRow>
//                 <input type="text" name="first-name" id="first-name" placeholder="Ad" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <input type="text" name="last-name" id="last-name" placeholder="Soyad" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
//                 </MDBRow>
//                 <hr/>
//                 <MDBRow>
//                 <input type="text" name="task-definition" id="task-definition" placeholder="Görev Tanımı" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <input type="date" name="birthdate" id="birthdate" placeholder="Doğum Tarihi" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <input type="tel" name="phone" id="phone" placeholder="(0___) ___ __ __" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" maxLength={11}/>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <div className="py-1.5 grid grid-cols-1 gap-y-8 sm:grid-cols-6">
//                     Cinsiyet :
//                     <div className="flex items-center gap-x-3">
//                     <input
//                         id="female"
//                         name="gender"
//                         type="radio"
//                         className="h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-600"
//                     />
//                     <label htmlFor="push-everything" className="block text-sm leading-6 text-gray-900">
//                         Kadın
//                     </label>
//                     </div>
//                     <div className="flex items-center gap-x-3">
//                     <input
//                         id="male"
//                         name="gender"
//                         type="radio"
//                         className="h-4 w-4 border-gray-300 text-indigo-600 focus:ring-indigo-600"
//                     />
//                     <label htmlFor="push-email" className="block text-sm leading-6 text-gray-900">
//                         Erkek
//                     </label>
//                     </div>
//                 </div>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <div className="py-1.5 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
//                     <div className="sm:col-span-3">
//                     <label for="city" className="sr-only">Şehir</label>
//                     <div>
//                         <select id="city" name="city"
//                         className="relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
//                         <option>İl Seçiniz</option>
//                         <option>Tokat</option>
//                         <option>Karabük</option>
//                         </select>
//                     </div>
//                     </div>
//                     <div className="sm:col-span-3">
//                     <label for="district" className="sr-only">İlçe</label>
//                     <div>
//                         <select id="district" name="district"
//                         className="relative block w-full rounded-t-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:z-10 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
//                         <option>İlçe Seçiniz</option>
//                         <option>Merkez</option>
//                         </select>
//                     </div>
//                     </div>
//                 </div>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <input type="email" name="email" id="email" placeholder="E-mail" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <input type="password" name="password" id="password" placeholder="Şifre" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
//                 </MDBRow>
//                 <hr />
//                 <MDBRow>
//                 <textarea id="about" name="about" rows="3" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder='Kendin hakkında bir şeyler yaz...'></textarea>
//                 </MDBRow>
//                 <div className="mt-6 flex items-center justify-end gap-x-6" >
//                     <MDBBtn type="submit"
//                         className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
//                     Kaydet
//                     </MDBBtn >
//                 </div>
//               </MDBCardBody>
//             </MDBCard>
//           </MDBCol>
//         </MDBRow>
//       </MDBContainer>
//     </section>
//     </Layout>
//   </>
//   )
// }
