import React from 'react'
import Layout from '@/components/Layout'
import Head from 'next/head'
import {
    MDBCol,
    MDBContainer,
    MDBRow,
    MDBCard,
    MDBCardBody,
  } from 'mdb-react-ui-kit';
import AddCategoryModal from '@/components/AddCategoryModal';

export default function AddCourse() {
  return (
    <>
    <Head>
      <title>VEDUS | Ders Ekle</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossOrigin="anonymous"/>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css" rel="stylesheet" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
    </Head>
    <Layout>
      <section>
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex items-baseline justify-between border-b border-gray-200 pb-6 pt-10">
              <h1 className="text-3xl font-bold tracking-tight text-gray-900">Ders Ekle :</h1>
            </div>
        </div>

        <div className="container py-4">
          <div className="lg:w-4/5 mx-auto flex flex-wrap">
            {/* Kişisel Bilgiler */}
            <MDBContainer>
                <MDBRow>
                    <MDBCol lg="4">
                        <MDBCard className="mb-4">
                        <MDBCardBody className="text-center">
                            <div className="mx-auto flex flex-wrap">
                            <img alt="ecommerce" className="mx-auto object-cover object-center rounded border border-gray-200" src="https://images.unsplash.com/photo-1537495329792-41ae41ad3bf0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"/>
                            </div>
                        </MDBCardBody>
                        </MDBCard>
                    </MDBCol>
                    <MDBCol lg="8">
                        <MDBCard className="mb-4">
                        <MDBCardBody>
                            <MDBRow className='py-2'>
                            <input type="text" name="course-title" id="course-title" placeholder="Ders İlanı Başlık" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
                            </MDBRow>
                            <hr />
                            <MDBRow className='py-2'>
                              <select id="category" name="category"
                                  className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                                  <option>Kategori Seçiniz</option>
                                  <option>Matematik</option>
                                  <option>Türkçe</option>
                              </select>
                            </MDBRow>
                            <hr />
                            <MDBRow className='py-2'>
                            <textarea id="description" name="description" rows="10" className="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder='İlan hakkında bir şeyler yaz...'></textarea>
                            </MDBRow>
                            <div className="mt-6 flex items-center justify-end gap-x-6" >
                                <AddCategoryModal/>
                                <button className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" type="submit">
                                 Ekle
                                </button>
                            </div>
                        </MDBCardBody>
                        </MDBCard>
                    </MDBCol>
                </MDBRow>
            </MDBContainer>
          </div>
        </div>
      </section>
    </Layout>
  </>
  )
}